### ISSUE TITLE
Package fails to install from deb on ROS Noetic

### ISSUE THREAD

**Issue by mikaelarguedas** [CopterExpress/ros_led#1]
The deb has an invalid path in the `postinst` script preventing it from being installed. It looks like the `ROS_DISTRO` is not detected properly when building the deb.
```
Setting setuid bit for ws281x_node
chmod: cannot access '/opt/ros//lib/ws281x/ws281x_node': No such file or directo
ry
dpkg: error processing package ros-noetic-ws281x (--configure):
 installed ros-noetic-ws281x package post-installation script subprocess returne
d error exit status 1
Errors were encountered while processing:
 ros-noetic-ws281x
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by okalachev** [comment]
Hi, @mikaelarguedas, thank you for the report! Can you please set the suid bit for the binary manually for now:

```bash
sudo chown root:root $(catkin_find ws281x ws281x_node)
sudo chmod +s $(catkin_find ws281x ws281x_node)
```

I'll investigate the problem later.

Any hints of what the problem may be related to are appreciated (it's not me who wrote the `postinst` script).

**Comment by mikaelarguedas** [comment]
thanks, I'm actually not using this package, just trying to make an image with all ROS Noetic packages and this is one of the few that don't succeed to install.

When building locally the postinst script does look correct. I suspect that in the environment building the debs the `ROS_DISTRO` environment variable is not set. Maybe some people more versed on the deb building environment like @tfoote or @nuclearsandwich would know what is the recommended way to build a path in a generated postinst script

**Comment by nuclearsandwich** [comment]
If the `ROS_DISTRO` environment variable is required at either build or runtime then a corresponding `build_depend` or `exec_depend` on the `ros_environment` package must be added to the package.xml.

If you wish to avoid the runtime dependency, adding it at build time and making the script into a template which is evaluated by CMake is an option.

Edit: I realize, the postinstall script may not be sourcing the noetic environment. My recommendation would be to generate the postinstall script as a template with the path determined from ros_environment at build time.

**Comment by Melmarkt** [comment]
Hi, I have the same problem as @mikaelarguedas, but on ROS Melodic.

**Comment by deadln** [comment]
@mikaelarguedas @nuclearsandwich I was responsible for release of ros_led packages in rosdistro but i didn't add any postinstall rules into [release repo](https://github.com/CopterExpress/ros_led-release). I think if problem appears only during build then add `ros_environment` as build dependency should be enough. But i don't know how to verify that the problem is solved except making a new version release in rosdistro, waiting for sync and trying to install via apt. There is [another way](https://gist.github.com/awesomebytes/196eab972a94dd8fcdd69adfe3bd1152) to build ROS deb package but i never got this error by building package like that. Prerelease build via ROS-buildfarm emulation doesn't show any issues either.

**Comment by mikaelarguedas** [comment]
Based on @nuclearsandwich recommendation I opened https://github.com/CopterExpress/ros_led/pull/2 with the added build dependency as the postinst script is generated at CMake time.

> But i don't know how to verify that the problem is solved except making a new version release in rosdistro, waiting for sync and trying to install via apt.

We could try to release a version with the patch and install the deb from the [testing repository](http://wiki.ros.org/TestingRepository) to test it before a sync happens

**Comment by deadln** [comment]
I just made sure that the package installation from test repository is successful. The fixed version of package will be available after upcoming Melodic and Noetic syncs.
