### ISSUE TITLE
issue regarding librosconsole.so in raspi 4, ubuntu 20.04

### ISSUE THREAD

**Issue by siddharthcb** [CopterExpress/ros_led#3]
hello,
I am facing an issue with librosconsole.so.

 when i launch the example.launch file.
it throws me an error saying 

```
/home/ubuntu/catkin_ws/devel/lib/ws281x/ws281x_node: error while loading shared libraries: librosconsole_log4cxx.so: cannot open shared object file: No such file or directory
[led-1] process has died [pid 7292, exit code 127, cmd /home/ubuntu/catkin_ws/devel/lib/ws281x/ws281x_node __name:=led __log:=/home/ubuntu/.ros/log/c367a89e-250c-11ec-bd2a-ddf33f5d5062/led-1.log].
log file: /home/ubuntu/.ros/log/c367a89e-250c-11ec-bd2a-ddf33f5d5062/led-1*.log
```

i certainly do not have the file` librosconsole_log4cxx.so` but i have` librosconsole.so` present in my system.
i reckon it is just the file name that i have to change somewhere but i am unable to figure out the path.
Any idea about it?

**Comment by okalachev** [comment]
Hi! It's the first time I see such an error.

Are you sure you have correct ROS installation on your system? Do other nodes work? Have you sourced ROS' `setup.bash`?

**Comment by siddharthcb** [comment]
yeah, I assure that ros is properly installed on this one.
I had got an another error prior to this:

`error while loading shared libraries: libxmlrpcpp.so: cannot open shared object file: No such file or directory
`
this got solved after installing: `sudo apt install libxmlrpcpp-dev`
But the one related to librosconsole is not solved.

[This link](https://www.codeleading.com/article/27565645310/) speaks of the exact problem but it did not work for me.

**Comment by okalachev** [comment]
Have you built `ws281x` package yourself? Were there any errors?

**Comment by sfalexrog** [comment]
Sounds like there's an issue sourcing the workspace.

@siddharthcb, I assume you're using ROS Noetic. Please confirm that you have the following files:

```bash
/opt/ros/noetic/lib/librosconsole_log4cxx.so
/opt/ros/noetic/lib/libxmlrpcpp.so
```

The first one comes from the `ros-noetic-rosconsole` package, which should have been installed as a dependency of `ros-noetic-ros-core`. The second one comes from `ros-noetic-xmlrpcpp`, which is a dependency of `ros-noetic-ros-comm` (which is, in turn, also a dependency of `ros-noetic-ros-core`).

---
Please provide more details on how you're running the node (what is the exact command, which user is running the command, output of the `env` command before you launch the node, what is your process of launching this file - every little bit helps!).

**Comment by siddharthcb** [comment]
I confirm both the files exist in the mentioned path.

I also confirm sourcing this:
```
source /opt/ros/noetic/setup.bash
source ~/catkin_ws/devel/setup.bash

```

I am running the example.launch file from the repo.

```
<launch>
    <node pkg="ws281x" name="led" type="ws281x_node" clear_params="true" output="screen">
        <param name="led_count" value="60"/>
        <param name="gpio_pin" value="13"/>
        <param name="brightness" value="255"/>
        <param name="strip_type" value="WS2811_STRIP_GRB"/>
        <param name="target_frequency" value="800000"/>
        <param name="dma" value="10"/>
        <param name="invert" value="false"/>
    </node>
</launch>
```
I have built ws281x from source and I also confirm that i can get this working just by using the ws281x library but i gotta run the script in sudo since i am using the PWM gpio 13.
I basically do not want to run under root and my SPI GPIO connection is also being used up so felt like giving it a try to use this package.

**Comment by siddharthcb** [comment]
hello,
I was able to solve my issue.
it was related to qt and qt was unable to include ros related libraries.

All i had to do was:
```
sudo apt install libxmlrpcpp-dev
vi /etc/ld.so.conf --> Add /usr/local/lib and /opt/ros/noetic/lib
/sbin/ldconfig -v
ldconfig
```

**Comment by siddharthcb** [comment]
but a small question, does the package work for pwm gpio 13?

I get error like:
```
Gpio 13 is illegal for LED channel 0
[FATAL] [1633589937.122624417]: [ws281x] native library init failed: Selected GPIO not possible
```

**Comment by okalachev** [comment]
Unfortunately I haven't checked with GPIO 13. We use GPIO 21 and works.

The library uses I2S interface to control the LED and actually may not work on all the pins.

@siddharthcb, have you got it working?

**Comment by siddharthcb** [comment]
> Unfortunately I haven't checked with GPIO 13. We use GPIO 21 and works.
> 
> The library uses I2S interface to control the LED and actually may not work on all the pins.
> 
> @siddharthcb, have you got it working?

i got it working. All the errors and solutions have been pushed to branch channel-1 in my forked repo. It works for channel-1 GPIOs.
Thank you for this package.
